baseURL: 'https://inarighas.github.io/my-personal-website/'
languageCode: "en-us"
title: "Ali's Personal Page"
theme: hugo-profile

Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ali's personal page"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "img/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 500 # default: 400
    lineHeight: 1.25 # default: 1.5
    textAlign: left # default: left

  # color:
  #   textColor: black
  #   secondaryTextColor: darkblue
  #   backgroundColor: egg
  #   secondaryBackgroundColor: egg
  #   primaryColor: black
  #   secondaryColor: light

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ali Saghiran."
    subtitle: "Welcome!"
    content: |-
      I am a Data scientist. In the past, I studied signal processing, mathematical modeling and statistics.
      I have worked (and still have interest) in Bayesian Modeling to study human cognition and particularly language skills.
      Right now, I am working as a data scientist for speech technologies in industry where I mainly build and train models for voice processing.
      Check my blogposts, I post in there, from time to time, some news & some useful stuff.
      
      To get a brief resumé, check down here ↓

      & for any request, feel free to reach me on social media!
    button:
      enable: true
      name: "Resume"
      url: "files/CV_english.pdf"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/inarighas
        - icon: fab fa-twitter
          url: https://www.twitter.com/inarighas
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ali-saghiran-a6a04390/
        - icon: fab fa-stack-overflow
          url: https://stackoverflow.com/users/9360793/inarighas
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    font: sans-serif
    title: "A brief outline of my professional journey"
    image: "/images/me.png"
    content: |-
      I'm **Ali Saghiran**, I have studied signal processing at Grenoble Institute of Technology (Grenoble INP) and did my PhD
       in Computational modeling and cognitive science at Grenoble Alpes University.
      During my PhD, I was interested in studying speech production and perception using bayesian/probabilistic modeling.
      
      I had work experience in both academia, as research assistant/engineer, and in industry as a software engineer.
      Currently, I am a Data Scientist and ML Engineer at ResileyesTx: I build and train models and pipelines for voice processing: automatic speech recognition & affective computing.  
      Also, I contribute to FOSS in my spare time!
    
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python, R, C/C++, Matlab, Julia"
        - "Training ML models using Scikit-lear"
        - "Deep learning using Pytorch, HuggingFace and tensorflow"
        - "Data viz and Dashboards using matplotlib, Bokeh, Streamlit etc.  "

  # # Experience
  experience:
    enable: True
    # title: "Custom Name"
    items:
      - job: "Data Scientist - Voice Specialist "
        company: "Resileyes Tx"
        companyUrl: "https://www.resileyes.com/"
        date: "Feb 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://www.resileyes.com/"
        content: |-
          - I developped language and speech processing modules for a mental health app: speech-to-text, automatic voice feature extraction,
          and emotion analysis APIs using deep learning models.
          - I had to develop & evaluate ML models for mental health diagnosis.
        Skills: Software Development · Python (Programming Language) · Data Analysis · Machine Learning · Microservice development · Data vizualisation"

      - job: "Research software Developer"
        company: "LPNC - CNRS"
        companyUrl: "https://lpnc.univ-grenoble-alpes.fr/"
        date: "May 2021 - Oct 2021"
        featuredLink:
          enable: true
          url: "https://fluence.prod.lamp.cnrs.fr/category/news/"
        info:
          enable: true
          content: As part of Fluence eFran project, I worked as a research engineer for more than 6 months.
        content: |-
          - Development and documentation of the BRAID model (collection of simulation programs of visual word processing tasks).
          - Probabilistic model programming and statistical analyses.
          - Release of [BRAID & BRAID-Phon](https://gricad-gitlab.univ-grenoble-alpes.fr/diardj/braid) source code.

      - job: "Teaching assistant"
        company: "Grenoble-Alpes University"
        companyUrl: "https://www.univ-grenoble-alpes.fr/"
        date: "Sep 2018 - May 2019"
        info:
          enable: true
        content: |-
          - Theoretical and practical courses at the Departments of Psychology & Mathematics
          - Practical courses: 'Introductory course to computer Science and Algorithmics using Python' & 'Object-oriented programming with Java' ~ 45 hours.
          - Courses and tutorials: 'Statistics and Data Analysis' ~ 35 hours.

  # Education
  education:
    enable: false
    # title: "Custom Name"
    # index: true
    items:
      - title: "PhD in Cognitive Science"
        school:
          name: "University of Grenoble Alpes, Grenoble, France"
          url: https://www.univ-grenoble-alpes.fr/
        date: "2017 - 2021"
        content: |-
          - Modeling of Visual word recognition and reading tasks within a Bayesian framework. 
          - Compare psychological theories and models of reading and reproduce using simulation experimental effects.  
      
      - title: "Master of Research in Cognitive Science"
        school:
          name: "Grenoble Institute of Technology "
          url: "https://phelma.grenoble-inp.fr/fr/formation/master-sciences-cognitives-parcours-cognition-naturelle-et-artificielle-cna-2#page-presentation"
        date: "2016 - 2017"

      - title: "Master of Engineering in Signal Processing"
        school:
          name: "Grenoble Institute of Technology "
          url: "https://phelma.grenoble-inp.fr/fr/formation/ingenieur-de-grenoble-inp-phelma-filiere-signal-image-communication-multimedia-sicom"
        date: "2014 - 2017"
        # content: |-
        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # # projects
  # projects:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Hugo Profile
  #       content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile.png
  #       featured:
  #         name: Demo
  #         link: https://hugo-profile.netlify.app
  #       # badges:
  #       #   - "Hugo"
  #       #   - "Bootstrap"
  #       #   - "Javascript"
  #       links:
  #         - icon: fa fa-envelope
  #           url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/hugo-profile
  #         - icon: fab fa-twitter
  #           url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  #     - title: Image Converter
  #       content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
  #       image: /images/projects/converter.jpg
  #       featured:
  #         name: Demo
  #         link: https://django-converter.herokuapp.com
  #       # badges:
  #       #   - "Django"
  #       #   - "Bootstrap"
  #       links:
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/converter

  #     - title: Hugo Profile V2
  #       content: A clean and simple Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile2.jpg
  #       featured:
  #         name: Demo V2
  #         link: https://hugo-profile-2.netlify.app
  #       # badges:
  #       #   - "Hugo"
  #       #   - "Bootstrap"
  #       #   - "Javascript"
  #       links:
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: |-
      Whether you have a question or just want to say hi, My inbox is always open:
      `a(dot)saghiran(at)gmail(dot)com`
    # email: gurusabarisha@gmail.com
    # btnName: Mail me

  footer:
    recentPosts: True
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #  instagram: https://instagram.com
    #  facebook: https://facebook.com
